---
abstract: 'Little framework for init.d scripts creation and manipulation.'
author:
  - 'Shamatrin Dmitriy'
build_requires:
  ExtUtils::MakeMaker: 0
  File::ShareDir: 0
  File::ShareDir::Install: 0
  POSIX: 0
  System::Process: 0.15
  Test::More: 0
  Time::HiRes: 0
configure_requires:
  File::ShareDir: 0
  File::ShareDir::Install: 0
  System::Process: 0.15
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: System-InitD
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: 0
  File::ShareDir: 0
  File::ShareDir::Install: 0
  POSIX: 0
  System::Process: 0.15
  Time::HiRes: 0
  perl: 5.006
resources:
  repository: https://github.com/justnoxx/system-initd.git
version: 1.24
