---
abstract: unknown
author:
  - 'Shamatrin D.'
build_requires:
  ExtUtils::MakeMaker: 0
  File::ShareDir: 0
  File::ShareDir::Install: 0
  POSIX: 0
  System::Process: 0.15
  Test::More: 0
  Time::HiRes: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  File::ShareDir: 0
  File::ShareDir::Install: 0
  POSIX: 0
  System::Process: 0.15
  Time::HiRes: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: System-InitD
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: 0
  File::ShareDir: 0
  File::ShareDir::Install: 0
  POSIX: 0
  System::Process: 0.15
  Time::HiRes: 0
  perl: 5.006
version: 1.16
