---
abstract: 'Little framework for init.d scripts creation and manipulation.'
author:
  - 'Shamatrin Dmitriy'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: System-InitD
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/justnoxx/system-initd.git
version: '1.26'
